spring:
  datasource:
    url: jdbc:mysql://39.106.21.141:3306/xsxs1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Kyh199765.
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

##redis
---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 300ms
    password:
    jedis:
      pool:
        max-idle: 10
        max-wait: -1ms
    lettuce:
      pool:
        max-idle: 8
      shutdown-timeout: 100ms

---
spring:
  #MQ配置
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #是否手动确认
    publisher-confirms: true
    #消息发送失败的回调函数
    publisher-returns: true
    template:
      retry:
        #授权
        enabled: true
        #委托
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        #并发消费者初始化值
        concurrency: 10
        #并发消费者的最大值
        max-concurrency: 20
        #每个消费者每次监听时可拉取处理的消息数量
        prefetch: 5
      #默认
      direct:
        retry:
          enabled: true
          max-attempts: 1
#日志
#logging.path=${user.dir}/logs
logging:
  path: /root/log
  file: ${logging.path}/boot-demo.log
  level:
    root: info
    com:
      ldy: info

---
#solr
spring:
  application:
    name: solr
  data:
    solr:
      host: http://localhost:8080/solr
server:
  port: 8081
